apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-channel
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-channel
  template:
    metadata:
      labels:
        app: frontend-channel
    spec:
      containers:
      - name: frontend
        # Make sure this matches your exact Artifact Registry path
        image: asia-southeast2-docker.pkg.dev/project-3ad3e57a/secure-banking-images/neobank-core:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: APP_SCRIPT
          value: "frontend-channel.py"
        - name: SWITCH_SERVICE_URL
          value: "http://payment-switch-service.app.svc.cluster.local:8081/api/v1/switch/process"
        - name: LEDGER_BALANCE_URL
          value: "http://core-ledger-service.app.svc.cluster.local:8082/ledger/balance"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-channel-service
  namespace: app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: frontend-channel