apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-channel
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-channel
  template:
    metadata:
      labels:
        app: frontend-channel
    spec:
      containers:
      - name: frontend
        image: asia-southeast2-docker.pkg.dev/project-3ad3e57a-ebe0-4fe5-b00/lab-images/banking:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - |
          sed -i '1s/^/import json\n/' $APP_SCRIPT;
          python3 $APP_SCRIPT;
        resources:
          requests:
            cpu: "20m"       
            memory: "64Mi"   
          limits:
            cpu: "100m"     
            memory: "128Mi"  
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10    
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/var/secrets"
          readOnly: true
        ports:
        - containerPort: 8080
        env:
        - name: APP_SCRIPT
          value: "frontend-channel.py"
        - name: SWITCH_SERVICE_URL
          value: "http://payment-switch-service.app.svc.cluster.local:8081/api/v1/switch/process"
        - name: LEDGER_BALANCE_URL
          value: "http://core-ledger-service.app.svc.cluster.local:8082/ledger/balance"
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store-gke.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "app-secrets-provider"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-channel-service
  namespace: app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: frontend-channel

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-channel-hpa
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-channel
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70