apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
  namespace: app
  labels:
    app: onboarding
    tier: middle-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onboarding
  template:
    metadata:
      labels:
        app: onboarding
    spec:
      containers:
      - name: onboarding
        image: asia-southeast2-docker.pkg.dev/project-3ad3e57a-ebe0-4fe5-b00/app-repo/banking:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/var/secrets"
          readOnly: true
        env:
        - name: APP_SCRIPT
          value: "onboarding.py"
        - name: DB_HOST
          value: "10.240.10.3"
        ports:
        - containerPort: 8083
          name: api-port
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8083
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store-gke.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "app-secrets-provider"

---
apiVersion: v1
kind: Service
metadata:
  name: onboarding
  namespace: app
  labels:
    app: onboarding
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: onboarding