apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-switch
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-switch
  template:
    metadata:
      labels:
        app: payment-switch
    spec:
      containers:
      - name: switch
        image: asia-southeast2-docker.pkg.dev/project-3ad3e57a-ebe0-4fe5-b00/lab-images/banking:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - |
          sed -i '1s/^/import json\n/' $APP_SCRIPT;
          python3 $APP_SCRIPT;
        resources:
          requests:
            cpu: "20m"       
            memory: "64Mi"   
          limits:
            cpu: "100m"     
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10      
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/var/secrets"
          readOnly: true
        ports:
        - containerPort: 8081
        env:
        - name: APP_SCRIPT
          value: "payment-switch.py"
        - name: LEDGER_SERVICE_URL
          value: "http://core-ledger-service.app.svc.cluster.local:8082/ledger/mutate"
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store-gke.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "app-secrets-provider"

---
apiVersion: v1
kind: Service
metadata:
  name: payment-switch-service
  namespace: app
  labels:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - name: http-metrics 
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: payment-switch


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-switch-hpa
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-switch
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70