apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-switch
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-switch
  template:
    metadata:
      labels:
        app: payment-switch
    spec:
      containers:
      - name: switch
        image: asia-southeast2-docker.pkg.dev/project-3ad3e57a/secure-banking-images/neobank-core:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: APP_SCRIPT
          value: "payment-switch.py"
        - name: LEDGER_SERVICE_URL
          value: "http://core-ledger-service.app.svc.cluster.local:8082/ledger/mutate"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-switch-service
  namespace: app
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: payment-switch