apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets-provider
  namespace: app
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/project-3ad3e57a-ebe0-4fe5-b00/secrets/banking-db-secret/versions/3"
        fileName: "db_credentials.json"